image: gitpod/workspace-full

tasks:
  - name: Init Laravel
    init: |
      if [ ! -f laravel-app/artisan ]; then
        composer create-project laravel/laravel laravel-app
      fi
      cd laravel-app
      composer install
      cp .env.example .env
      sed -i 's/SESSION_DRIVER=.*/SESSION_DRIVER=file/' .env
      php artisan key:generate
      mkdir -p database
      touch database/database.sqlite
    command: |
      cd laravel-app
      php artisan serve --host=0.0.0.0 --port=8000

  - name: Init API
    init: |
      cd api
      npm install
    command: |
      node api/index.js

ports:
  - port: 8000
    onOpen: open-preview
    name: laravel
  - port: 8080
    onOpen: open-preview
    name: api
